version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    parallelism: 4
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - checkout
      - run : |
              chmod +x node.sh
             
